name: HighBrushes
main: com.karusmc.highbrushes.HighBrushes
version: 0.01
description: A goBrushes fork/rewrite. Create mountains higher than Kevaasaurus
depend: [WorldEdit]
author: [goCreative Arcaniax, PanteLegacy]

commands:
  
  #<------ Main command ------>
  
  highbrushes:
    aliases: [highbrush, hbrushes, hbrush, hb]
    description: Main HighBrushes command
    usage: /highbrushes [subcommand]
    permission: highbrushes.command
    
  # <------ Subcommands ------>
    
  "highbrushes about":
    aliases: [about, a]
    description: Displays plugin info
    usage: /highbrushes about
    permission: highbrushes.about
    
  "highbrushes help":
    aliases: [help, h]
    description: Displays help information about the plugin
    usage: /highbrushes help [(page)]
    permission: highbrushes.help
    
  "highbrushes list":
    aliases: [list, ;]
    description: Returns a list of availible brushes
    usage: /highbrushes list [(page)]
    permission: highbrushes.list
    
  "highbrushes reload":
    aliases: [reload, re, r]
    description: Reloads the plugin component
    usage: /highbrushes reload [(component)]
    permission: highbrushes.reload
    
  "highbrushes toggle":
    aliases: [toggle, t]
    description: Enables and disabled a brush 
    usage: /highbrushes toggle [(auto-rotation/bounding-box/flat/mountain)]
    permission: highbrushes.toggle
    
  # <------ Brush subcommands ------>
  
  "highbrushes brush":
    aliases: [brush, b]
    description: Select and rotate between brushes
    usage: /highbrushes brush [(brush name)]
    permission: highbrushes.brush.select
  
  "highbrushes info":
    aliases: [info, i]
    description: Displays curretn brush information
    usage: /highbrushes info
    permission: highbrushes.brush.info
  
  "highbrushes intensity":
    aliases: [intensity, int]
    description: Change the brush intensity
    usage: /highbrushes intensity [(intensity)]
    permission: highbrushes.brush.intensity
    
  "highbrushes undo":
    aliases: [undo, u]
    description: Undo your previous actions
    usage: /highbrushes undo [(number of steps)]
    permission: highbrushes.brush.undo
    
  "highbrushes size":
    aliases: [size, s]
    description: Change the brush size
    usage: /highbrushes size [(size)]
    permission: highbrushes.brush.size
    
    
# <------ Permissions ------>

permissions:
  highbrushes.*:
    children:
      highbrushes.command: true
      highbrushes.about: true
      highbrushes.help: true
      highbrushes.list: true
      highbrushes.reload: true
      highbrushes.toggle: true
      highbrushes.brush.*: true
      
  highbrushes.brush.*:
    children:
      highbrushes.brush.select: true
      highbrushes.brush.info: true
      highbrushes.brush.intensity: true
      highbrushes.brush.undo: true
      highbrushes.brush.use: true
      highbrushes.brush.size: true
      
      
  highbrushes.command:
    default: true
    
  highbrushes.about:
    default: false
    
  highbrushes.help:
    default: false
 
  highbrushes.list:
    default: false
    
  highbrushes.reload:
    default: false
    
  highbrushes.toggle:
    default: false
    
  
  highbrushes.brush.select:
    default: false
    
  highbrushes.brush.info:
    default: false
    
  highbrushes.brush.intensity:
    default: false
    
  highbrushes.brush.undo:
    default: false
    
  highbrushes.brush.use:
    default: false
    
  highbrushes.brush.size:
    default: false
      
  
    
    
    

